name = "WeatherAppServer"
uuid = "e30c4db3-cc3e-4888-b5ef-7f6ce7b7124f"  # Generate a UUID: `using UUIDs; UUIDs.uuid4()`
version = "0.1.0"

[deps]
HTTP = "1.10.16" # or the latest version - Pinned to this version
JSON = "0.21.4" # or the latest version - Pinned to this version
Dates = "1.0" # or the latest version - Pinned to this version

[compat]
julia = "1.11.5" # or your Julia version